spring:
  application:
    name: competition-service
server:
  port: 0
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
