
spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: person-service
server:
  port: 8001

log:
  level:
    org:
      jfullam: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/