
spring:
  application:
    name: stat-service
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

stats:
  collection:
    description: Baseball Statistics