spring:
  application:
    name: zuul-proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
logging:
  level:
    org:
      jfullam: DEBUG
server:
  port: 8000
zuul:
  ignoredServices: '*'
  routes:
    people:
      path: /people/**
      serviceId: person-service
      stripPrefix: false
    teams:
      path: /teams/**
      serviceId: person-service
      stripPrefix: false
    events:
      path:  /events/**
      serviceId: competition-service
      stripPrefix: false
    locations:
      path:  /locations/**
      serviceId: event-service
      stripPrefix:  false
    stats:
      path: /stats/**
      serviceId: stat-service
