spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfullam/league-mgmt
          searchPaths: config-repo
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
